# Generated by Django 5.1.5 on 2025-02-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edudata", "0002_alter_schoollocation_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolimage",
            name="caption",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schoolimage",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("EXTERIOR", "Exterior"),
                    ("INTERIOR", "Interior"),
                    ("FACILITY", "Facility"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=15,
            ),
        ),
    ]
