# Generated by Django 5.1.5 on 2025-02-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edudata", "0004_school_is_deleted_school_verified_school_verified_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school",
            old_name="school_id",
            new_name="school_code",
        ),
        migrations.AddField(
            model_name="schoolcontact",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
