# Generated by Django 5.1.5 on 2025-03-09 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_blacklistedtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlacklistedToken",
        ),
    ]
