# Generated by Django 5.1.5 on 2025-03-13 20:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_delete_blacklistedtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_image_url",
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.CustomUser.profile_image_path,
                verbose_name="profile picture",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("USER", "User"),
                    ("BUSINESS_OWNER", "Business Owner"),
                ],
                default="USER",
                max_length=30,
            ),
        ),
    ]
