# Generated by Django 5.1.5 on 2025-03-16 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthdata", "0004_alter_healthfacility_verified_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthfacility",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="health_facility_verifier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
